export { default as authApiRouter } from './auth.routes.js'
export { default as userApiRouter } from './user.routes.js'
export { default as AdministrativosApiRouter } from './administrativos.routes.js'
export { default as EstudiantesApiRouter } from './estudiantes.routes.js'
export { default as AcademicosApiRouter } from './academicos.routes.js'
export { default as MateriasApiRouter } from './materias.routes.js'
export { default as UploadApiRouter } from './upload.routes.js'
