export { default as AuthService } from './auth.service.js'
export { default as UserService } from './user.service.js'
export { default as AdministrativosService } from './administrativos.service.js'
export { default as EstudiantesService } from './estudiantes.service.js'
export { default as AcademicosService } from './academicos.service.js'
export { default as MateriasService } from './materias.service.js'
